# Generated by Django 3.2.5 on 2022-05-31 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betogether', '0002_learnerproject_groupproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whishList', models.CharField(max_length=128)),
                ('groupProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betogether.groupproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betogether.groupproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betogether.groupproject')),
                ('learnerProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betogether.learnerproject')),
            ],
        ),
    ]
